import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import SplineBackground from '@components/spline';
import ScrollingBackground from '@components/scroll';

const Container = styled.div`
  /* Add your container styles here */
`;

const SplineCard = styled.div`
  height: 100vh;
  width: 100%;
`

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SplineCard>
      <SplineBackground splineSceneUrl="https://prod.spline.design/1pLL8hQ2rWkXmjMn/scene.splinecode" />
      </SplineCard>
      <ScrollingBackground />
    </Container>
  );
};

export default Home;