import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';
import WelcomeDIV from '@components/wlcm';
import CultureDiv from '@components/culture'
import SwiperComponent from '@components/swiper';
import ContactSec from '@components/contact';

const Container = styled.div`
  /* Add your container styles here */
`;


const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Arslan&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WelcomeDIV></WelcomeDIV>
      <CultureDiv></CultureDiv>
      <SwiperComponent></SwiperComponent>
      <ContactSec></ContactSec>
    </Container>
  );
};

export default Home;